### ISSUE TITLE
Deeper comparisons with the tool

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/oscal-deep-diff#19]
# User Story:

As an OSCAL user, I need to be able to detect deeper changes in OSCAL documents with configuration that allows for better reproducibility.

### More Details

Currently, the OSCAL-deep-diff tool can, given two documents, compare objects (nested maps) directly including their sub-objects, as well as optimally matching arrays of objects together by their properties, so that the matched array pairs have the minimum number of differences between them. This covers many scenarios that can apply to OSCAL documents, such as minor edits to **catalogs**, or **groups** that have been renamed.

The tool does not handle one scenario that can happen a lot during major revisions: sub-objects moved from one item of an array to another. For example, within a catalog, a **control** could move from one **group** to another between revisions, or **parts** from multiple **controls** could be consolidated into one **control** (or dispersed into multiple **controls**).

## Goals:

This is an Epic issue, which means it is a issue that links to multiple sub-issues.
- [x] Create YAML definitions for configuration parameters (as the number of configuration options & usage scenarios increases, relying on collections of command line flags makes for an increasingly frustrating experience)
- [x] Add models for json object primitives, with helper functions for resolving pointers and, matching
- [x] Remove hanging references to old/new documents (as well as "added" and "removed") and replace with the terms left/right
- [x] Keep track of unmatched items of each array, and match them together

**No longer in scope of this issue:**
- Add the option to specify other string-similarity algorithms
- Add the option to prompt the user for how a given array should be matched if no constraint has been provided or learned
- Add the option to save all "learned" constraints in order to replicate the same comparison with another set of documents

*Note some of these issues will be broken into smaller tickets, see usnistgov/OSCAL#988 for more details.*

## Dependencies:

No active issues are dependencies.

## Acceptance Criteria

For all sub-tasks:
- [ ] readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by nikitawootten-nist** [comment]
## 1/14/2021
It has been a while since this issue has been updated. Currently the YAML schema has been implemented, and the rewrite adding helper objects for the JSON object primitives is in progress. An algorithm for tracking unmatched items of arrays has also been implemented, but needs to be adjusted once the helper objects are complete.

This week I plan on finishing up that change as well as adjusting the new matching/scoring algorithm.
