### ISSUE TITLE
Production release readiness & publication in MIDAS

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/oscal-deep-diff#43]
# User Story:

As a NIST OSCAL team member, in order to ensure this project is well-designed, implemented, tested, and documented, I want itemized list of NIST publication requirements for publishing research software, status, and supported evidence for individual items per and other relevant guidelines.

*NOTE: this issue is derived from usnistgov/metaschema-node#16*

## Goals:

The following NIST requirements must be met:
- [x] [NIST S 1801.03](https://inet.nist.gov/system/files/documents/2021/12/29/final-s-1801_03-ver-3.pdf) (supplemented by [this checklist](https://inet.nist.gov/system/files/documents/2022/04/27/checklist-for-software-form-2022-04-27%20.pdf))
    - [x] **How do you expect your code/software to be used** *(choose 1)*:
        - ~~Code is informational (e.g. part of the supplemental information in a narrative publication) and not intended for re-use~~
        - **Code itself is intended for re-use (e.g. in a specific scientific area) or the public is being invited to contribute to it**
    - [x] **Developing and Testing:**
        - [x] A testing plan was developed, followed, and documented. The testing plan is available at a specified link. (see usnistgov/OSCAL#44)
        - [x] Continuous testing was conducted during updates and new builds.
        - [x] Code includes appropriate IT security and privacy controls. (DNA)
    - [x] **Documenting:**
        - [x] Documentation is available as appropriate as: *(choose 1)*
            - **Integrated with the source code**
            - ~~On separate web pages (e.g. nist.gov, pages.nist.gov)~~
            - ~~In a separate publication~~
            - ~~Other~~
        - [x] Documentation includes, as appropriate:
            - [x] A readme
            - [x] Function-level documentation
            - ~~Information about how a binary was produced~~
            - [x] System requirements and prerequisites (e.g., OS version, memory, dependencies): **Available in `package.json`
            - [x] Installation instructions
            - [x] User instructions/guides
            - [x] API Specification
            - [x] A changelog file (included in GitHub releases)
            - [x] Specification of maturity level (i.e. is the software still being developed,, are you expecting feedback on performance and usability, is the project completed)
            - [x] A communication to users of your intent to provide (or not provide) support
    - [x] **License and disclaimers:**
        - [x] NIST license and disclaimers 
        - [x] External collaborators who were part of this project have been credited
        - [x] Third-party software licenses permit modification and/or redistribution
            - [x] Appropriate licensing is included
            - [x] Files modified by NIST contain notice that modifications are released to the public domain as appropriate
- [x] [Fair Principles](https://github.com/usnistgov/opensource-repo/blob/3039806ce93fe5afd6a9535edf305188ee196346/fair-software.md) (supplemented by [this checklist](https://github.com/usnistgov/opensource-repo/blob/3039806ce93fe5afd6a9535edf305188ee196346/fair-software.md#make-it-fair-in-ten-easy-steps))
    - [x] Findable (Will be satisfied by MIDAS entry)
        - [x] (Meta)data are assigned a globally unique and persistent identifier
        - [x] Data are described with rich metadata (defined by R1 below)
        - [x] Metadata clearly and explicitly include the identifier of the data they describe
        - [x] (Meta)data are registered or indexed in a searchable resource
    - [x] Accessible (satisfied by NPM)
        - [x] (Meta)data are retrievable by their identifier using a standardised communications protocol 
        - [x] Metadata are accessible, even when the data are no longer available
    - [x] Interoperable (satisfied by NPM)
        - [x] (Meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation.
        - [x] (Meta)data use vocabularies that follow FAIR principles
        - [x] (Meta)data include qualified references to other (meta)data
    - [x] Reusable (satisfied by NPM)
        - [x] (Meta)data are richly described with a plurality of accurate and relevant attributes 
            - [x] (Meta)data are released with a clear and accessible data usage license
            - [x] (Meta)data are associated with detailed provenance
            - [x] (Meta)data meet domain-relevant community standards
